name: Push

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        uses: ./.github/actions/test

  build:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: ./.github/actions/build-controller
        with:
          tags: ${{ github.sha }} latest
      #     image: IMAGE
      #
      # - name: Push To Quay
      #   uses: redhat-actions/push-to-registry@v2
      #   if: ${{ github.repository == 'ORG/REPO'}}
      #   with:
      #     image: IMAGE
      #     tags: ${{ github.sha }} latest
      #     registry: quay.io/QUAY_ORG
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_PASSWORD }}

      # - name: Set expiration
      #   uses: ./.github/actions/set-expiration
      #   with:
      #     repository: QUAY_ORG/QUAY_REPO
      #     tag: ${{ github.sha }}
      #     expiration: +1 week
      #     token: ${{ secrets.QUAY_OAUTH_TOKEN }}
